baseurl = "https://example.com/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "red"
  showMenuItems = 3
  fullWidthTheme = true
  centerTheme = false

[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
      [[languages.en.menu.main]]
        identifier = "test"
        name = "Bacon and cheese"
        url = "/post/Bacon and cheese"
